#_byobu_sourced=1 . /usr/bin/byobu-launch

#[[ -e /usr/local/texlive/2012/bin ]] && PATH=/usr/local/texlive/2012/bin/x86_64-linux:$PATH

#export WINEPREFIX=$HOME/wine32
#export WINEARCH=win32
export RUBY_HOME=$HOME/.rvm/gems/ruby-2.2.0/
export PAGER="most"
export PATH=~/bin:~/.local/bin:$PATH
export PATH=$RUBY_HOME:$PATH
#export JAVA_HOME=/usr/lib/jvm/java-7-oracle/jre
#export WORKON_HOME=~/envs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
#export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export EDITOR='vim'
export JAVA_HOME=/usr/lib/jvm/java-8
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH


